### ISSUE TITLE
DeflateEncoder should own its Options

### ISSUE THREAD

**Issue by Pr0methean** [zopfli-rs/zopfli#15]
I'm having difficulty integrating DeflateEncoder into https://github.com/Pr0methean/zip-next/ because of its lifetime parameter and the fact that it borrows Options. ZipWriter and its compression-algorithm-specific delegate GenericZipWriter both own all their members, so there isn't a natural choice of lifetime. Why not just let DeflateEncoder own the Options?

**Comment by AlexTMjugador** [comment]
This is a nice idea! [Given that `Options` is now `Copy`](https://github.com/zopfli-rs/zopfli/pull/16), there really is no reason to take it by reference in function parameters.

I'd also like to apply this idea to the `compress` function, but that'd introduce a semver-breaking change I don't fancy, as that's likely to slow down the adoption of the new release, so let's don't do it for now.
