### ISSUE TITLE
Make ZOPFLI_MASTER_BLOCK_SIZE an option

### ISSUE THREAD

**Issue by Pr0methean** [zopfli-rs/zopfli#18]
I have a program that creates large PNGs (up to 48 MiB of raw pixel data, but usually 12 or 16 MiB) and uses Zopfli as the deflater for PNG encoding. At these sizes, compression ratios are usually between 99.4% and 99.9%. I suspect the compression would go much faster if I could specify a larger ZOPFLI_MASTER_BLOCK_SIZE, e.g. 4 MiB, so that compression operated on fewer blocks. I'm currently using only about 20GiB RAM on a c7g.16xlarge (which has 124GiB).

**Comment by AlexTMjugador** [comment]
Indeed a bigger master block size could help in this case. Have you tried using the `DeflateEncoder` wrapped on a `BufWriter` of a custom, large capacity? Currently, the [`compress` function is just a more ergonomic frontend for that](https://github.com/zopfli-rs/zopfli/blob/e4096652b613d77136e36424ef0d7c6745c699c3/src/deflate.rs#L153-L178).

**Comment by Pr0methean** [comment]
Thanks; I'll suggest that to the maintainer of oxipng.

**Comment by Pr0methean** [comment]
I'm trying to use a BufWriter in a fork of Oxipng, but it's failing an end-to-end test. Any clue what I might be doing wrong?
```
impl Deflater for BufferedZopfliDeflater {
    fn deflate(&self, data: &[u8], max_size: &AtomicMin) -> PngResult<Vec<u8>> {
        #[allow(clippy::needless_update)]
        let options = Options {
            iteration_count: self.iterations,
            maximum_block_splits: self.max_block_splits,
            ..Default::default() // for forward compatibility
        };
        let mut out = Cursor::new(Vec::with_capacity(self.output_buffer_size));
        let mut buffer = BufWriter::with_capacity(
            self.input_buffer_size,
            DeflateEncoder::new(
                options,
                Default::default(),
                &mut out,
            ),
        );
        let result = (|| -> io::Result<()> {
            buffer.write_all(data)?;
            buffer.into_inner()?.finish()?;
            Ok(())
        })();
        result.map_err(|e| PngError::new(&e.to_string()))?;
        let out = out.into_inner();
        println!("Compressed {} -> {} bytes", data.len(), out.len());
        if max_size.get().is_some_and(|max| max < out.len()) {
            Err(PngError::DeflatedDataTooLong(out.len()))
        } else {
            Ok(out)
        }
    }
}
```

**Comment by Pr0methean** [comment]
Update: found the issue - Oxipng is using `zlib_compress` rather than `compress`.

**Comment by Pr0methean** [comment]
Is it possible `zlib_compress` could support this as well? That, not `compress`, is what Oxipng is using.

**Comment by Pr0methean** [comment]
Even copying the `zlib_compress` code into my code doesn't work, because `HashingAndCountingRead` is in a private crate.

**Comment by AlexTMjugador** [comment]
> Is it possible `zlib_compress` could support this as well? That, not `compress`, is what Oxipng is using.

It'd be necessary to redesign its API, which is a breaking change, but other than that yes, it's possible and doable.

**Comment by AlexTMjugador** [comment]
The API has been redesigned in v0.8.0 to provide `GzipEncoder` and `ZlibEncoder` structs, analogous to `DeflateEncoder`. Using these structs, users can tune block sizes and other advanced compression options for each of the supported compression formats. Therefore, I consider this issue resolved :tada:
