### ISSUE TITLE
panic at reading file

### ISSUE THREAD

**Issue by Arian-p1** [zopfli-rs/zopfli#19]
```thread 'main' panicked at 'ERROR: Failed to read file!: TextDecode("Found invalid encoding")', src/helpers/gen_funcs.rs:16:10```

**Comment by AlexTMjugador** [comment]
Hi! There is no way that this library may cause that panic, as it doesn't contain the source file mentioned in the panic message. Can you please describe your execution environment, what are you doing and what did you expect in more detail? Otherwise, I can't act on this issue, and I'll have to close it eventually.

**Comment by Arian-p1** [comment]
> Hi! There is no way that this library may cause that panic, as it doesn't contain the source file mentioned in the panic message. Can you please describe your execution environment, what are you doing and what did you expect in more detail? Otherwise, I can't act on this issue, and I'll have to close it eventually.

i was listening to music and it got crash after choosing another song 
I guess it have trouble to read some file 
I tried to found the code but as u said its in lib 
and why it will crash isn't that better to just return the error ?
Also the files are mp3

**Comment by Arian-p1** [comment]
also can you give me the info that i need to know to add the a dir to queue and add shuffle option

**Comment by AlexTMjugador** [comment]
I don't think I can effectively help you with this problem, sorry. Zopfli is a compression tool, not a music player. My guess is that you tried to play a file with badly formatted text metadata and the music player didn't handle it gracefully. Please contact the authors of the music player you're using, they'll most likely be able to help you, or at least give you a better picture of what's going on.

**Comment by Arian-p1** [comment]
> I don't think I can effectively help you with this problem, sorry. Zopfli is a compression tool, not a music player. My guess is that you tried to play a file with badly formatted text metadata and the music player didn't handle it gracefully. Please contact the authors of the music player you're using, they'll most likely be able to help you, or at least give you a better picture of what's going on.

at least can you make it to avoid panic ?

**Comment by mqudsi** [comment]
This doesn't have anything to do with zopfli, maybe you are using an app that is using zopfli?

**Comment by AlexTMjugador** [comment]
> at least can you make it to avoid panic ?

For the reasons stated above, I don't think I can do anything on my end to avoid this panic.

**Comment by Arian-p1** [comment]
> This doesn't have anything to do with zopfli, maybe you are using an app that is using zopfli?

I'm opening it with alacritty and fish as shell

**Comment by mqudsi** [comment]
(I’m a fish dev too, you’re in luck!)

Zopfli (this project) is not an executable. You can’t “run” this project. You ran an app that *used* this project.
