### ISSUE TITLE
(Primary) copyright holder(s) of this project?

### ISSUE THREAD

**Issue by nc7s** [zopfli-rs/zopfli#45]
Hi, I stumbled upon this project when packaging Rust code in Debian. We are pretty strict about copyright, so I have to figure out what to put in our copyright file.

There are no "Copyright (c)" lines in the COPYING file, README, or any source file, or similar "owner" language, that can point to someone to hold the copyright. Please consider add one to clarify. Thank you ;)

**Comment by AlexTMjugador** [comment]
Hey, thanks for reaching out! I'm happy to hear someone considered packaging it for Debian :+1: 

Defining the ownership of this crate is, in my view, a bit convoluted. Historically, @carols10cents created it by incrementally porting the original Zopfli C code to Rust. ([The original Zopfli repository](https://github.com/google/zopfli) also lacks "Copyright (c)" lines, but explicitly credits Lode Vandevenne and Jyrki Alakuijala for the "Zopfli Compression Algorithm".) More recently, contributors like me have stepped up to maintain and enhance the crate, sharing repository write and `crates.io` publishing permissions.

So, I'm having a hard time deciding who, in particular, deserves to be recognized as the main "owner". Carol's work was foundational, but it wouldn't exist without the original implementation by Vandevenne and Alakuijala. Furthermore, using the `zopfli` crate for streaming compression, an arguably important use case, wouldn't have been possible without the contributors who came after.

For the purposes of Debian packaging, would it be sufficient to consider a group like "Zopfli crate contributors" as the owner entity? Please let me know how that sounds!

**Comment by nc7s** [comment]
Hi Alex!

I understand that people sometimes work in tacit consent, not by crystal clear rules. That's totally fine by me ;)

The "X (project) contributors" notion is not uncommon. As long as you are happy with it, it's OK! Although adjusting it a bit to something like "zopfli-rs contributors" might be more clear in Debian context.

**Comment by AlexTMjugador** [comment]
A "zopfli-rs contributors" owner string sounds good to me. Let's see if any other contributor wants to chime in with other opinion or idea... :smile:

**Comment by mqudsi** [comment]
I think we all defer to Alex on this one, and his reply is gracious and considerate.

**Comment by nc7s** [comment]
Since people who appeared so far all agreed and no one objected, I take it that "zopfli-rs contributors" is accepted?

**Comment by nc7s** [comment]
Oh and, I apologize for missing this, the LICENSE file that's seemingly copied over from the C project actually has this near the end:

https://github.com/zopfli-rs/zopfli/blob/472f6338ae9b6bbebed976c212a503b24f0511ad/COPYING#L189

Also, the CONTRIBUTORS file hasn't been updated since the beginning of this port, but it's the same in the original implementation and that got accepted, so I guess doesn't matter.

**Comment by AlexTMjugador** [comment]
> Since people who appeared so far all agreed and no one objected, I take it that "zopfli-rs contributors" is accepted?

After ~2 weeks the question was made with the replies received so far, it seems there's some sort of consensus on this matter, yes. I'll soon update the CONTRIBUTORS file of the project to indicate that this port is owned by the "zopfli-rs contributors," while also acknowledging the previous contributors of the original C implementation.
