### ISSUE TITLE
Mildly suspicious owner

### ISSUE THREAD

**Issue by alecmocatta** [zopfli-rs/zopfli#6]
[Bejolithic](https://crates.io/users/bejolithic) is an owner of this crate, as of https://github.com/zopfli-rs/zopfli/issues/1.

I just happened to notice that all 3 other crates they own are copies of other crates, renamed, stripped of attribution and relicensed:

https://crates.io/crates/forage -> https://crates.io/crates/maimo: https://github.com/FuzzrNet/Forage/issues/6
https://crates.io/crates/wasmpng -> https://crates.io/crates/wasimage: https://github.com/datatrash/wasm-png/issues/1
https://crates.io/crates/bbcli -> https://crates.io/crates/wingcli: https://github.com/losfair/blueboat/issues/90

Probably innocuous, but thought it might be worth raising to nip in the bud potential for a supply-chain attack on users of this crate.

**Comment by dfrankland** [comment]
Thanks for raising up this issue!

There were many, many more instances of not only crates, but entire repos, blog posts and more that I found blatantly copied without any form of attribution. This behavior is definitely suspicious and there's nowhere I can find that Bejolithic contributed to zopfli-rs, so I have removed this user from the organization.

**Comment by kornelski** [comment]
This looks wrong indeed. These aren't just forks, but crates with completely replaced authorship metadata without any credit, and inappropriately changed license.

I've removed them from zopfli owners.

**Comment by alecmocatta** [comment]
Thanks for the swift action both! Agreed, the more I looked the more dodgy that account seemed. And their sudden near-universal disappearance is interesting: https://bio.link/bejolithic https://volt.fm/bejolithic https://keybase.io/bejolithic https://contra.com/bejolithic https://www.reddit.com/r/KeybaseProofs/comments/v0f9m8/my_keybase_proof_redditbejolithic/ [Ahmad Ainul Rizki](https://www.facebook.com/bejolithic) https://twitter.com/bejolithic https://vero.co/bejolithic

Closing as resolved.
